#??????
server:
  servlet:
    context-path: /app1
  tomcat:
    uri-encoding: utf-8

#
spring:
  profiles:
    active: prod
  thymeleaf:
    cache: false
    prefix: classpath:/static/
    suffix: .jsp

#
dog:
  name: egg_core
  age: ${random.int}
  hobby:
    chicken
    pork
    bread

